# Generated by Django 5.0.2 on 2024-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_participant_name_alter_participant_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantworkout',
            name='score',
            field=models.DurationField(),
        ),
    ]
