# Generated by Django 5.0.2 on 2024-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_participantworkout_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantworkout',
            name='score',
            field=models.FloatField(),
        ),
    ]
